### PR TITLE
feat(parse): Update parse function

### PR DESCRIPTION
**Pull request by lawvs**
- [x] Complement `Github Event Type`
- [x] Update `parse` function
- [x] Update test

### CODE REVIEW

**Comment by azu** [comment]
Can I review it?

**Comment by lawvs** [comment]
いいよ

**Review by azu — APPROVED** [review]
LGTM.

📝 Delete following events because these events are deprecated.

- GistEvent
- DownloadEvent

**Comment by azu** [comment]
Thanks.
I've released https://github.com/azu/parse-github-event/releases/tag/1.1.0

**Pull request merged**
